//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlmacenSobrasUbicaciones
    {
        public long ID { get; set; }
        public long IDAlmacenSobras { get; set; }
        public int Cantidad { get; set; }
        public string CodUbicacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
    
        public virtual AlmacenSobras AlmacenSobras { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
    }
}
