//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticulosOperacionesTallas
    {
        public int ID { get; set; }
        public int IdArticuloOperacion { get; set; }
        public Nullable<int> Posicion { get; set; }
        public string TallaArticulo { get; set; }
        public int IdUtillajeTalla { get; set; }
        public Nullable<double> ProductividadCalculada { get; set; }
        public Nullable<double> ProductividadTallaUtillaje { get; set; }
    
        public virtual ArticulosOperaciones ArticulosOperaciones { get; set; }
        public virtual UtillajesTallas UtillajesTallas { get; set; }
    }
}
