//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticulosOperaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArticulosOperaciones()
        {
            this.ArticulosOperacionesTallas = new HashSet<ArticulosOperacionesTallas>();
        }
    
        public int ID { get; set; }
        public int IdArticulo { get; set; }
        public Nullable<int> NumeroOperacion { get; set; }
        public string NumeroOperacionAnterior { get; set; }
        public Nullable<int> NumeroOperacionSiguiente { get; set; }
        public int IdOperacion { get; set; }
        public string Descripcion { get; set; }
        public string Observaciones { get; set; }
        public string CodSeccion { get; set; }
        public string CodConexion { get; set; }
        public Nullable<bool> MostrarMaterias { get; set; }
        public string CodUtillaje { get; set; }
        public Nullable<decimal> TiempoPreparacion { get; set; }
        public Nullable<decimal> TiempoEjecucion { get; set; }
        public Nullable<decimal> TiempoOperario { get; set; }
        public Nullable<double> Eficiencia { get; set; }
        public Nullable<double> CosteTiempo { get; set; }
        public Nullable<double> CosteIndirectoInterno { get; set; }
        public Nullable<double> CosteOperacion { get; set; }
        public Nullable<double> CosteIndirectoSubcontrata { get; set; }
        public Nullable<bool> PosibilidadSubcontratar { get; set; }
        public Nullable<bool> PosibilidadInterna { get; set; }
        public Nullable<bool> PrioridadSubcontratar { get; set; }
        public Nullable<double> CosteTiempoMaestro { get; set; }
        public Nullable<double> CosteOperacionMaestro { get; set; }
        public Nullable<int> TipoProceso { get; set; }
    
        public virtual Operaciones Operaciones { get; set; }
        public virtual Secciones Secciones { get; set; }
        public virtual Utillajes Utillajes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticulosOperacionesTallas> ArticulosOperacionesTallas { get; set; }
    }
}
