//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulos()
        {
            this.ArticulosMateriales = new HashSet<ArticulosMateriales>();
            this.OrdenesFabricacion = new HashSet<OrdenesFabricacion>();
            this.OrdenesFabricacionMateriales = new HashSet<OrdenesFabricacionMateriales>();
            this.StockArticulos = new HashSet<StockArticulos>();
            this.ArticulosTallas = new HashSet<ArticulosTallas>();
        }
    
        public int ID { get; set; }
        public string CodigoArticulo { get; set; }
        public string Descripcion { get; set; }
        public string UnidadDeMedida { get; set; }
        public double Precio { get; set; }
        public bool Bloqueado { get; set; }
        public string CodigoCliente { get; set; }
        public string NombreCliente { get; set; }
        public string Modelo { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Certificado { get; set; }
        public Nullable<bool> ImportadoERP { get; set; }
        public string CodFamilia { get; set; }
        public string CodSubFamilia { get; set; }
        public short GrupoTallaActual { get; set; }
        public string RutaImagen { get; set; }
        public Nullable<int> IdArticuloDetalleCliente { get; set; }
        public double CantidadUnidadLogistica { get; set; }
        public Nullable<double> MinimoSaldos { get; set; }
        public Nullable<double> MaximoSaldos { get; set; }
        public double Ciclo { get; set; }
        public string ObservacionEtiqueta1 { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    
        public virtual ArticulosDetalleCliente ArticulosDetalleCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticulosMateriales> ArticulosMateriales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesFabricacion> OrdenesFabricacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesFabricacionMateriales> OrdenesFabricacionMateriales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockArticulos> StockArticulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticulosTallas> ArticulosTallas { get; set; }
    }
}
