//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticulosTallasDetalleCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArticulosTallasDetalleCliente()
        {
            this.ArticulosTallas = new HashSet<ArticulosTallas>();
        }
    
        public int Id { get; set; }
        public string SKU { get; set; }
        public string SuTalla { get; set; }
        public string UvexCodigoEtiqueta { get; set; }
        public string SuTallaHaix { get; set; }
        public string MaspicaCodigoEtiqueta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticulosTallas> ArticulosTallas { get; set; }
    }
}
