//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITAR_MOVIMIENTOS_PREPAQUETES
    {
        public int Id { get; set; }
        public string CodPrepaquete { get; set; }
        public string CodUbicacionAnterior { get; set; }
        public string CodUbicacion { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
    }
}
