//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BancadasConfiguracionesPins
    {
        public int IdBancada { get; set; }
        public string PinBuzzer { get; set; }
        public string PinLed { get; set; }
        public double ContadorPaquetes { get; set; }
        public bool EsContadorPaquetesAutomatico { get; set; }
        public bool AvisarFinPaquete { get; set; }
        public bool AvisarFinTarea { get; set; }
    
        public virtual Bancadas Bancadas { get; set; }
    }
}
