//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarquillasConsumos
    {
        public int Id { get; set; }
        public int IdContenidoBarquilla { get; set; }
        public int IdOperacionConsumo { get; set; }
        public System.DateTime FechaConsumo { get; set; }
    
        public virtual BarquillasContenidos BarquillasContenidos { get; set; }
        public virtual OrdenesFabricacionOperaciones OrdenesFabricacionOperaciones { get; set; }
    }
}
