//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarquillasContenidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BarquillasContenidos()
        {
            this.BarquillasConsumos = new HashSet<BarquillasConsumos>();
        }
    
        public int Id { get; set; }
        public int IdOrden { get; set; }
        public string Talla { get; set; }
        public double Cantidad { get; set; }
        public int IdBarquilla { get; set; }
    
        public virtual Barquillas Barquillas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarquillasConsumos> BarquillasConsumos { get; set; }
        public virtual OrdenesFabricacion OrdenesFabricacion { get; set; }
    }
}
