//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campos_ERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campos_ERP()
        {
            this.OrdenesFabricacion = new HashSet<OrdenesFabricacion>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHAPEDIDO { get; set; }
        public string NOMBRECLI { get; set; }
        public string DOMICILIOENVIO { get; set; }
        public Nullable<int> PEDIDO { get; set; }
        public Nullable<int> LINEAPEDIDO { get; set; }
        public string DESCRIPCIONARTICULO { get; set; }
        public string SUMODELOEXPEDICION { get; set; }
        public string OBSERVACIONESEXPEDICION { get; set; }
        public Nullable<int> IDOF { get; set; }
        public string RAZONSOCIALCLI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesFabricacion> OrdenesFabricacion { get; set; }
    }
}
