//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciclos
    {
        public int Id { get; set; }
        public string Ciclo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdBancada { get; set; }
    
        public virtual Bancadas Bancadas { get; set; }
    }
}
