//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlSobrasLog
    {
        public int Id { get; set; }
        public string CodigoArticulo { get; set; }
        public string Talla { get; set; }
        public double CantidadPropuesta { get; set; }
        public double CantidadFinal { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdPedido { get; set; }
        public string CodigoOrden { get; set; }
    }
}
