//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidenciasBancadasRegistros
    {
        public int Id { get; set; }
        public Nullable<int> IdBancada { get; set; }
        public int IdIncidenciaEstado { get; set; }
        public int IdIncidenciaTipo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaInicioCorregida { get; set; }
        public Nullable<System.DateTime> FechaFinCorregida { get; set; }
        public Nullable<System.DateTime> FechaInicioValidada { get; set; }
        public Nullable<System.DateTime> FechaFinValidada { get; set; }
        public Nullable<int> IdOrdenFabricacionOperacionTallaCantidad { get; set; }
    
        public virtual Bancadas Bancadas { get; set; }
        public virtual IncidenciasEstados IncidenciasEstados { get; set; }
        public virtual IncidenciasTipos IncidenciasTipos { get; set; }
    }
}
