//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioLecturas
    {
        public long Id { get; set; }
        public int IdInventario { get; set; }
        public string IdContenedor { get; set; }
        public Nullable<long> IdPaquete { get; set; }
        public System.DateTime FechaLectura { get; set; }
    
        public virtual Contenedores Contenedores { get; set; }
        public virtual Inventarios Inventarios { get; set; }
        public virtual Paquetes Paquetes { get; set; }
    }
}
