//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidaciones
    {
        public int ID { get; set; }
        public string Periodo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public short CodigoEmpresa { get; set; }
        public short EjercicioAlbaran { get; set; }
        public string SerieAlbaran { get; set; }
        public int NumeroAlbaran { get; set; }
        public short Orden { get; set; }
        public System.Guid LineasPosicion { get; set; }
        public int Agente { get; set; }
        public decimal C__Comision { get; set; }
        public int ID_Criterio { get; set; }
    }
}
