//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaquinasRegistrosDatos
    {
        public string CodigoEtiqueta { get; set; }
        public int IdTarea { get; set; }
        public int Productividad { get; set; }
        public string IpAutomata { get; set; }
        public int PosicionMaquina { get; set; }
        public int IdPuesto { get; set; }
        public int IdOperacion { get; set; }
        public string CodigoOrden { get; set; }
        public int IdOrden { get; set; }
        public string Talla { get; set; }
        public string TallaUtillaje { get; set; }
        public int IdOperario { get; set; }
        public double Ciclo { get; set; }
        public bool PiezaIntroducida { get; set; }
        public int Pares { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
