//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MercanciasDepositos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MercanciasDepositos()
        {
            this.Paquetes = new HashSet<Paquetes>();
        }
    
        public long ID { get; set; }
        public string Taller { get; set; }
        public string Direccion { get; set; }
        public string Localidad { get; set; }
        public string Telefono { get; set; }
        public string Contacto { get; set; }
        public Nullable<System.DateTime> FechaDeposito { get; set; }
        public string PersonaEmisora { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Consumido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paquetes> Paquetes { get; set; }
    }
}
