//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MercanciasRecepcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MercanciasRecepcion()
        {
            this.Paquetes = new HashSet<Paquetes>();
        }
    
        public long ID { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public string AlbaranProveedor { get; set; }
        public string Proveedor { get; set; }
        public string ProveedorSage { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> EntradaTransformacion { get; set; }
        public string TipoEntrada { get; set; }
        public Nullable<decimal> TotalCompras { get; set; }
        public Nullable<int> NumeroPaquetes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paquetes> Paquetes { get; set; }
    }
}
