//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperacionesControles
    {
        public int Id { get; set; }
        public int IdOperacion { get; set; }
        public int IdTipoMaquina { get; set; }
        public double TiempoInicio { get; set; }
        public double TiempoBaseEjecucion { get; set; }
        public double TiempoUtillajeEjecucion { get; set; }
        public double TiempoCambioBarquilla { get; set; }
    
        public virtual MaquinasTipos MaquinasTipos { get; set; }
        public virtual Operaciones Operaciones { get; set; }

    }
}
