//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operaciones()
        {
            this.ArticulosOperaciones = new HashSet<ArticulosOperaciones>();
            this.OperacionesControles = new HashSet<OperacionesControles>();
            this.OrdenesFabricacionOperaciones = new HashSet<OrdenesFabricacionOperaciones>();
            this.PreciosLaboralesSubcontratas = new HashSet<PreciosLaboralesSubcontratas>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public string Observaciones { get; set; }
        public string CodSeccion { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
        public Nullable<double> CosteTiempo { get; set; }
        public Nullable<double> CosteIndirectoInterno { get; set; }
        public Nullable<double> ParesHoraEstimados { get; set; }
        public Nullable<double> CosteHoraSubcontrata { get; set; }
        public Nullable<double> CosteOperacion { get; set; }
        public Nullable<double> CosteIndirectoSubcontrata { get; set; }
        public Nullable<bool> CosteConfirmado { get; set; }
        public Nullable<decimal> TiempoEjecucion { get; set; }
        public Nullable<decimal> TiempoPreparacion { get; set; }
        public Nullable<decimal> TiempoOperario { get; set; }
        public Nullable<double> Eficiencia { get; set; }
        public Nullable<bool> PosibilidadSubcontratar { get; set; }
        public Nullable<bool> PosibilidadInterna { get; set; }
        public Nullable<bool> PrioridadSubcontratar { get; set; }
        public string PadreArbol { get; set; }
        public string Ciclo { get; set; }
        public Nullable<int> TipoProceso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticulosOperaciones> ArticulosOperaciones { get; set; }
        public virtual Secciones Secciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacionesControles> OperacionesControles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesFabricacionOperaciones> OrdenesFabricacionOperaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreciosLaboralesSubcontratas> PreciosLaboralesSubcontratas { get; set; }
    }
}
