//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesFabricacionPaquetes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenesFabricacionPaquetes()
        {
            this.OrdenesFabricacionPaquetesTallas = new HashSet<OrdenesFabricacionPaquetesTallas>();
            this.OrdenesFabricacionPaquetesUtilizados = new HashSet<OrdenesFabricacionPaquetesUtilizados>();
        }
    
        public long Id { get; set; }
        public int IdOrdenFabricacionOperacionTallaCantidadEjecucion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public double Cantidad { get; set; }
        public bool SobrasOperacionSiguiente { get; set; }
        public string IdContenedor { get; set; }
        public Nullable<System.DateTime> FechaAsociacion { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdMaquinaConsumo { get; set; }
        public Nullable<int> IdOperario { get; set; }
        public Nullable<int> Productividad { get; set; }
    
        public virtual Contenedores Contenedores { get; set; }
        public virtual Maquinas Maquinas { get; set; }
        public virtual Operarios Operarios { get; set; }
        public virtual OrdenesFabricacionOperacionesTallasCantidadEjecucion OrdenesFabricacionOperacionesTallasCantidadEjecucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesFabricacionPaquetesTallas> OrdenesFabricacionPaquetesTallas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesFabricacionPaquetesUtilizados> OrdenesFabricacionPaquetesUtilizados { get; set; }
    }
}
