//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesFabricacionOperaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenesFabricacionOperaciones()
        {
            this.BarquillasConsumos = new HashSet<BarquillasConsumos>();
            this.OrdenesFabricacionOperacionesTallas = new HashSet<OrdenesFabricacionOperacionesTallas>();
            this.OrdenesFabricacionPaquetesBorrar = new HashSet<OrdenesFabricacionPaquetesBorrar>();
            this.PaquetesConsumosInternos = new HashSet<PaquetesConsumosInternos>();
            this.PrepaquetesConsumidos = new HashSet<PrepaquetesConsumidos>();
            this.TalleresPaquetesEnvios = new HashSet<TalleresPaquetesEnvios>();
            this.TalleresPaquetesRecepciones = new HashSet<TalleresPaquetesRecepciones>();
        }
    
        public int ID { get; set; }
        public int IdOrdenFabricacion { get; set; }
        public string NumeroOperacion { get; set; }
        public string NumeroOperacionAnterior { get; set; }
        public string NumeroOperacionSiguiente { get; set; }
        public string Descripcion { get; set; }
        public string Observaciones { get; set; }
        public string CodSeccion { get; set; }
        public string CodConexion { get; set; }
        public Nullable<bool> MostrarMaterias { get; set; }
        public string CodUtillaje { get; set; }
        public Nullable<decimal> TiempoPreparacion { get; set; }
        public Nullable<decimal> TiempoEjecucion { get; set; }
        public Nullable<decimal> TiempoOperario { get; set; }
        public Nullable<double> Eficiencia { get; set; }
        public Nullable<double> CosteTiempo { get; set; }
        public Nullable<double> CosteIndirectoInterno { get; set; }
        public Nullable<double> CosteOperacion { get; set; }
        public Nullable<double> CosteIndirectoSubcontrata { get; set; }
        public Nullable<bool> PosibilidadSubcontratar { get; set; }
        public Nullable<bool> PosibilidadInterna { get; set; }
        public Nullable<bool> PrioridadSubcontratar { get; set; }
        public Nullable<double> ParesHoraEstimados { get; set; }
        public Nullable<double> CosteHoraSubcontrata { get; set; }
        public Nullable<bool> CosteConfirmado { get; set; }
        public Nullable<int> TipoProceso { get; set; }
        public Nullable<int> IdTicketCalculo { get; set; }
        public Nullable<int> IdOperacionMaestra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarquillasConsumos> BarquillasConsumos { get; set; }
        public virtual Operaciones Operaciones { get; set; }
        public virtual OrdenesFabricacion OrdenesFabricacion { get; set; }
        public virtual Secciones Secciones { get; set; }
        public virtual TicketCalculos TicketCalculos { get; set; }
        public virtual Utillajes Utillajes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesFabricacionOperacionesTallas> OrdenesFabricacionOperacionesTallas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesFabricacionPaquetesBorrar> OrdenesFabricacionPaquetesBorrar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaquetesConsumosInternos> PaquetesConsumosInternos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrepaquetesConsumidos> PrepaquetesConsumidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalleresPaquetesEnvios> TalleresPaquetesEnvios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalleresPaquetesRecepciones> TalleresPaquetesRecepciones { get; set; }
    }
}
