//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesFabricacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenesFabricacion()
        {
            this.BarquillasContenidos = new HashSet<BarquillasContenidos>();
            this.OrdenesFabricacionCantidad = new HashSet<OrdenesFabricacionCantidad>();
            this.OrdenesFabricacionMateriales = new HashSet<OrdenesFabricacionMateriales>();
            this.OrdenesFabricacionObservaciones = new HashSet<OrdenesFabricacionObservaciones>();
            this.OrdenesFabricacionOperaciones = new HashSet<OrdenesFabricacionOperaciones>();
            this.PrePaquetes = new HashSet<PrePaquetes>();
            this.StockArticulos = new HashSet<StockArticulos>();
            this.TalleresPaquetesEnvios = new HashSet<TalleresPaquetesEnvios>();
            this.TalleresPaquetesRecepciones = new HashSet<TalleresPaquetesRecepciones>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdPedido { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public string Codigo { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public bool Acabada { get; set; }
        public string UnidadMedida { get; set; }
        public string CodigoArticulo { get; set; }
        public Nullable<System.Guid> LineasPosicion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> Revision { get; set; }
        public Nullable<System.DateTime> FechaEntregaSage { get; set; }
        public Nullable<System.DateTime> FechaFinalizado { get; set; }
        public Nullable<int> IDCAMPOERP { get; set; }
        public int Tipo { get; set; }
        public Nullable<int> Agrupacion { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarquillasContenidos> BarquillasContenidos { get; set; }
        public virtual Campos_ERP Campos_ERP { get; set; }
        public virtual OrdenesFabricacionTipos OrdenesFabricacionTipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesFabricacionCantidad> OrdenesFabricacionCantidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesFabricacionMateriales> OrdenesFabricacionMateriales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesFabricacionObservaciones> OrdenesFabricacionObservaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesFabricacionOperaciones> OrdenesFabricacionOperaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrePaquetes> PrePaquetes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockArticulos> StockArticulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalleresPaquetesEnvios> TalleresPaquetesEnvios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalleresPaquetesRecepciones> TalleresPaquetesRecepciones { get; set; }
    }
}
