//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesFabricacionPaquetesTallas
    {
        public int Id { get; set; }
        public long IdOrdenesFabricacionPaquetes { get; set; }
        public string Talla { get; set; }
    
        public virtual OrdenesFabricacionPaquetes OrdenesFabricacionPaquetes { get; set; }
    }
}
