//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesFabricacionMaterialesTallas
    {
        public int ID { get; set; }
        public int IdOrdenesFabricacionMateriales { get; set; }
        public Nullable<int> Posicion { get; set; }
        public string TallaArticulo { get; set; }
        public Nullable<int> IdTallaMaterial { get; set; }
        public Nullable<decimal> CorrectorCantidad { get; set; }
    
        public virtual OrdenesFabricacionMateriales OrdenesFabricacionMateriales { get; set; }
    }
}
