//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaletsMERCADONA
    {
        public long NumPalet { get; set; }
        public string LotePalet { get; set; }
        public string Producto { get; set; }
        public string Almacen { get; set; }
        public string LotePlantillas1 { get; set; }
        public string LotePlantillas2 { get; set; }
        public string LotePlantillas3 { get; set; }
        public System.DateTime FechaHora { get; set; }
        public int Cantidad { get; set; }
        public string GS1 { get; set; }
        public string SSCC { get; set; }
    
        public virtual AlmacenesMERCADONA AlmacenesMERCADONA { get; set; }
        public virtual ProductosMERCADONA ProductosMERCADONA { get; set; }
    }
}
