//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoNoFabricar
    {
        public int ID { get; set; }
        public Nullable<int> IdPedido { get; set; }
        public Nullable<System.Guid> LineaOrden { get; set; }
        public Nullable<int> CodigoEmpresa { get; set; }
    }
}
