//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerBIPagina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PowerBIPagina()
        {
            this.UsuariosAD = new HashSet<UsuariosAD>();
        }
    
        public int ID { get; set; }
        public int IDSector { get; set; }
        public int IDGrupo { get; set; }
        public string Pagina { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual PowerBIGrupo PowerBIGrupo { get; set; }
        public virtual PowerBISector PowerBISector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosAD> UsuariosAD { get; set; }
    }
}
