//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrePaquetesAgrupaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrePaquetesAgrupaciones()
        {
            this.PrePaquetes = new HashSet<PrePaquetes>();
        }
    
        public string CodigoEtiqueta { get; set; }
        public int NumeroAgrupacion { get; set; }
        public string Talla { get; set; }
        public double Cantidad { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string CodUbicacion { get; set; }
        public Nullable<System.DateTime> FechaAsociacion { get; set; }
        public Nullable<int> EspacioVagonId { get; set; }
        public Nullable<int> IdAgrupacionMaquina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrePaquetes> PrePaquetes { get; set; }
        public virtual TrenesVagonesEspacios TrenesVagonesEspacios { get; set; }
        public virtual Ubicaciones Ubicaciones { get; set; }
    }
}
