//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELACIONPEDIDOS
    {
        public string subpedido { get; set; }
        public short codigoempresa { get; set; }
        public short ejerciciopedido { get; set; }
        public string seriepedido { get; set; }
        public int numeropedido { get; set; }
        public System.Guid lineasposicion { get; set; }
        public string estado { get; set; }
    }
}
