//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockArticulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockArticulos()
        {
            this.StockArticulosTallas = new HashSet<StockArticulosTallas>();
        }
    
        public long Id { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public string CodigoArticulo { get; set; }
        public string IdContenedor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<int> IdOrdenFabricacion { get; set; }
        public int IdTipoStock { get; set; }
        public bool Disponible { get; set; }
        public string CabeceraReferencia { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaVerificacion { get; set; }
        public Nullable<int> IdOperarioCreacion { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Contenedores Contenedores { get; set; }
        public virtual Operarios Operarios { get; set; }
        public virtual OrdenesFabricacion OrdenesFabricacion { get; set; }
        public virtual StockArticulosTipos StockArticulosTipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockArticulosTallas> StockArticulosTallas { get; set; }
    }
}
