//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsCantidad
    {
        public int Id { get; set; }
        public int IdTicket { get; set; }
        public double Cantidad { get; set; }
        public int IdOrdenFabricacionCantidad { get; set; }
        public int IdOrdenFabricacionOperacionTallaCantidad { get; set; }
    
        public virtual OrdenesFabricacionCantidad OrdenesFabricacionCantidad { get; set; }
        public virtual OrdenesFabricacionOperacionesTallasCantidad OrdenesFabricacionOperacionesTallasCantidad { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
