//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrenesVagonesEspacios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrenesVagonesEspacios()
        {
            this.PrePaquetes = new HashSet<PrePaquetes>();
            this.PrePaquetesAgrupaciones = new HashSet<PrePaquetesAgrupaciones>();
        }
    
        public int Id { get; set; }
        public string CodigoEtiqueta { get; set; }
        public int IdTrenVagon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrePaquetes> PrePaquetes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrePaquetesAgrupaciones> PrePaquetesAgrupaciones { get; set; }
        public virtual TrenesVagones TrenesVagones { get; set; }
    }
}
