//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuariosAD()
        {
            this.UsuariosADAplicaciones = new HashSet<UsuariosADAplicaciones>();
            this.PowerBIPagina = new HashSet<PowerBIPagina>();
        }
    
        public int ID { get; set; }
        public string UsuarioAD { get; set; }
        public Nullable<bool> Acceso { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string UsuarioAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string UsuarioBaja { get; set; }
        public Nullable<decimal> Planta { get; set; }
        public Nullable<int> IDImpresora { get; set; }
        public string RutaBandeja { get; set; }
        public string ImpresoraPlanificador { get; set; }
    
        public virtual Impresoras Impresoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosADAplicaciones> UsuariosADAplicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PowerBIPagina> PowerBIPagina { get; set; }
    }
}
