//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtillajesTallas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UtillajesTallas()
        {
            this.ArticulosOperacionesTallas = new HashSet<ArticulosOperacionesTallas>();
            this.UtillajesTallasColeccion = new HashSet<UtillajesTallasColeccion>();
        }
    
        public int ID { get; set; }
        public string CodUtillaje { get; set; }
        public string TallaUtillaje { get; set; }
        public Nullable<double> Productividad { get; set; }
        public Nullable<int> DimensionX { get; set; }
        public Nullable<int> DimensionY { get; set; }
        public Nullable<int> Posicion { get; set; }
        public Nullable<int> TotalComponentes { get; set; }
        public string ImpresionMarcaje1 { get; set; }
        public string ImpresionMarcaje2 { get; set; }
        public string ImpresionMarcaje3 { get; set; }
        public string FicheroImpresionMarcaje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticulosOperacionesTallas> ArticulosOperacionesTallas { get; set; }
        public virtual Utillajes Utillajes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UtillajesTallasColeccion> UtillajesTallasColeccion { get; set; }
        public virtual UtillajesTallasRendimiento UtillajesTallasRendimiento { get; set; }
    }
}
