//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtillajesTallasRendimiento
    {
        public int IdUtillajeTalla { get; set; }
        public Nullable<short> UnidadesPorPlancha { get; set; }
    
        public virtual UtillajesTallas UtillajesTallas { get; set; }
    }
}
